### PR TITLE
[Style]: add glow color effect to icons/cards on hover

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Issue Addressed
This PR resolves issue #59  

## Proposed Changes and Benefits 

This pull request improves the user experience by introducing glowing random colored icons on hover and adding random colored borders to cards when hovered over. These enhancements not only enhance the aesthetics of the interface but also bring several benefits:

### Benefits:

1. **Interactive Visual Feedback:** Glowing icons on hover provide immediate and interactive visual feedback to users, making the application more engaging and user-friendly.

2. **Highlighting Important Elements:** By adding colored borders to cards when hovered, we draw attention to these elements, making it clear that they are clickable or interactive. This improves the overall user experience by guiding users to relevant actions.

3. **Modern and Attractive Design:** These enhancements align with modern design trends, giving the application a fresh and appealing look, which can be especially important for retaining and attracting users.

4. **Improved User Engagement:** With these visual improvements, users are more likely to interact with the icons and cards, resulting in improved user engagement and satisfaction.

5. **Accessibility:** Glowing effects and colored borders can also be beneficial for users with disabilities, as they provide clear visual cues for interactive elements.

### Before this PR
harmony

### After this PR
[Harmony-Code.webm](https://github.com/DhanushNehru/HarmonyCode/assets/130365071/75b5811c-9c11-43ae-95f0-c724df54cf6f)

## Notes to Reviewers

@DhanushNehru please review this PR.
Thanks

### CODE REVIEW

**Review by DhanushNehru — APPROVED** [review]

**Comment by DhanushNehru** [comment]
Looks amazing, Thank you @harmeetsingh11

**Comment by harmeetsingh11** [comment]
@DhanushNehru please add `hacktoberfest-accepted` label to the PR.
Thanks

**Comment by bellsofaba** [comment]
> ## Issue Addressed
> This PR resolves issue #59
> 
> ## Proposed Changes and Benefits
> This pull request improves the user experience by introducing glowing random colored icons on hover and adding random colored borders to cards when hovered over. These enhancements not only enhance the aesthetics of the interface but also bring several benefits:
> 
> ### Benefits:
> 1. **Interactive Visual Feedback:** Glowing icons on hover provide immediate and interactive visual feedback to users, making the application more engaging and user-friendly.
> 2. **Highlighting Important Elements:** By adding colored borders to cards when hovered, we draw attention to these elements, making it clear that they are clickable or interactive. This improves the overall user experience by guiding users to relevant actions.
> 3. **Modern and Attractive Design:** These enhancements align with modern design trends, giving the application a fresh and appealing look, which can be especially important for retaining and attracting users.
> 4. **Improved User Engagement:** With these visual improvements, users are more likely to interact with the icons and cards, resulting in improved user engagement and satisfaction.
> 5. **Accessibility:** Glowing effects and colored borders can also be beneficial for users with disabilities, as they provide clear visual cues for interactive elements.
> 
> ## Screenshots:
> ### Before this PR
> harmony
> 
> ### After this PR
>  Harmony-Code.webm 
> ## Notes to Reviewers
> @DhanushNehru please review this PR. Thanks

It looks like phenomenal work was done here! Just passing through. 👯

**Comment by DhanushNehru** [comment]
Yeah @bellsofaba

**Comment by harmeetsingh11** [comment]
Thanks @bellsofaba , @DhanushNehru

**Pull request merged**
