### PR TITLE
added google authentication  

### PR DESCRIPTION
**Pull request by HarshMakadiya**
In this PR I have added google OAuth using firebase please look into it and ping me if any changes are required.

### CODE REVIEW

**Comment by HarshMakadiya** [comment]
@DhanushNehru Please look into the checks and tell me if I should make any changes that are required.

**Comment by DhanushNehru** [comment]
Hi @HarshMakadiya can you view the above vercel deployment status & also let me know if any constant environment variables to be configured, and the required steps involved

**Comment by HarshMakadiya** [comment]
@DhanushNehru yes you need to add your own variable of firebase authentication in env. That's why vercel is giving error.

**Comment by DhanushNehru** [comment]
@HarshMakadiya  I have added & it seems it doesn't work as expected, not sure if anything is missed, you can check the vercel deployment output and investigate

**Comment by HarshMakadiya** [comment]
@DhanushNehru Popup is showing but not opening because of not putting the allowed domain there. Below is an example can you put this https://harmony-code-f7xlb0t58-dhanushnehru.vercel.app/ inside your domain allowed in firebase and check after that?

image

**Comment by HarshMakadiya** [comment]
Sorry, @DhanushNehru I was just resolving the conflict of gitignore I didn't know it would merge into the main. First, check this branch from your end and then merge it.

**Comment by DhanushNehru** [comment]
Thanks @HarshMakadiya , I appreciate your work

**Comment by DhanushNehru** [comment]
Hi @HarshMakadiya seems due to some merge factors the google sign in feature button is not visible, can you sync the repo again and create another PR ?

**Comment by HarshMakadiya** [comment]
@DhanushNehru yeah just a minute.

**Comment by DhanushNehru** [comment]
I found out that it is commented, now uncommented i guess, just want you to verify once @HarshMakadiya

**Comment by DhanushNehru** [comment]
Sure @HarshMakadiya

**Comment by DhanushNehru** [comment]
@HarshMakadiya it was commented and I resolved it, thanks for your quick response

**Comment by HarshMakadiya** [comment]
@DhanushNehru Great!. I was looking at my local server and It was working. So everything is alright now? If you need any help ping me.

**Pull request merged**
