### PR TITLE
Gitpod usage reference added

### LINKED ISSUE #6: Include how to use gitpod for this repo, in the readme
List the steps to start working on this project via gitpod in the readme

For example, refer the below readme
https://github.com/DhanushNehru/breakout-game

### PR DESCRIPTION
**Pull request by RavindraP04**
I have added the gitpod usage steps in the readme,  It does not need any command to  start the server because, on opening the link of gitpod it automatically runs `npm i` and `npm run dev` to start the server

closes #6

### CODE REVIEW

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Please add this gitpod in the end of the readme file

**Review by DhanushNehru — APPROVED** [review]

**Comment by DhanushNehru** [comment]
Please resolve merge conflicts @RavindraP04

**Comment by RavindraP04** [comment]
> Please resolve merge conflicts @RavindraP04

Done

**Comment by RavindraP04** [comment]
@DhanushNehru Please add `hacktoberfest` labels

**Pull request merged**
