### PR TITLE
Made the Menu Mobile Responsive

### PR DESCRIPTION
**Pull request by tanish0912**
Screenshot 2024-10-12 at 1 04 07 AM
Screenshot 2024-10-12 at 1 04 16 AM

The website has been optimized for mobile responsiveness, incorporating a hamburger menu for a more streamlined and user-friendly browsing experience on mobile devices.

### CODE REVIEW

**Comment by tanish0912** [comment]
Any update?

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Hi @tanish0912 please remove the .env file , credentials should not be hardcoded !!!

**Comment by tanish0912** [comment]
I have removed the env file. Please let me know if any modifications needed.
Thanks, happy to help.

**Comment by tanish0912** [comment]
Thanks, Happy to contribute!

**Comment by tanish0912** [comment]
Please mark this as hacktoberfest accepted.

**Comment by aakarsh-2004** [comment]
Did this PR count towards hacktoberfest @tanish0912 ?

**Comment by DhanushNehru** [comment]
Yes @aakarsh-2004

**Pull request merged**
